name: Lance Ball
title: Software Developer
org: Lance Ball
base_url: ''

twitter: http://twitter.com/lanceball
github: http://github.com/lance
tumblr: http://blog.lanceball.com

profiles:
  production:
    base_url: http://lance.github.io/
    deploy:
      host: github_pages
      branch: master
